### ISSUE TITLE
CodeText autocompletion moves cursor focus when typing

### ISSUE THREAD

**Issue by haxmeister** [haje61/Tk-CodeText#1]
When typing a word you have used before, a small window drops down to allow you to auto-complete the word. However, this small dropdown menu takes the focus and interferes with typing. This needs to appear but leave focus in the text window so that the user can continue typing and select an autocompletion only when an appropriate one appears.

**Comment by haje61** [comment]
This is as designed. All editors I have used worked like this. And yes, sometimes annoying. I minimize my annoyance by setting a long pop wait time of 1200 ms. Would not know actually how to make it differently, it would not lift the annoyance only replace it with another one. By the way, this is an issue for App::Codit. It's the WordCompletion plugin.

**Comment by haje61** [comment]
To be fair, the WordCompletion plugin is the last one that I added. It has the least mileage. And could use lots of improvements.
